=begin
#Aliseeks API

#AliExpress product searching and product details retrieval API. 

OpenAPI spec version: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'date'

module AliseeksApi
  class RealtimeCurrency
    
    AUD = 'AUD'.freeze
    BRL = 'BRL'.freeze
    CAD = 'CAD'.freeze
    CHF = 'CHF'.freeze
    CLP = 'CLP'.freeze
    EUR = 'EUR'.freeze
    GBP = 'GBP'.freeze
    IDR = 'IDR'.freeze
    KRW = 'KRW'.freeze
    NZD = 'NZD'.freeze
    PLN = 'PLN'.freeze
    RUB = 'RUB'.freeze
    SEK = 'SEK'.freeze
    SGD = 'SGD'.freeze
    TRY = 'TRY'.freeze
    UAH = 'UAH'.freeze
    USD = 'USD'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = RealtimeCurrency.constants.select { |c| RealtimeCurrency::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #RealtimeCurrency" if constantValues.empty?
      value
    end
  end
end
