=begin
#Aliseeks API

#AliExpress product searching and product details retrieval API. 

OpenAPI spec version: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'spec_helper'
require 'json'

# Unit tests for AliseeksApi::SearchApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SearchApi' do
  before do
    # run before each test
    @instance = AliseeksApi::SearchApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SearchApi' do
    it 'should create an instance of SearchApi' do
      expect(@instance).to be_instance_of(AliseeksApi::SearchApi)
    end
  end

  # unit tests for realtime_search
  # Searches AliExpress in realtime 
  # @param realtime_search_request Realtime search request body 
  # @param [Hash] opts the optional parameters
  # @return [RealtimeSearchResponse]
  describe 'realtime_search test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for search
  # Searches AliExpress in non-realtime. Uses the Aliseeks.com datasource which is continually updated from AliExpress. 
  # @param search_request Search request body 
  # @param [Hash] opts the optional parameters
  # @return [SearchResponse]
  describe 'search test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for search_best_selling
  # Retrieves best selling products from AliExpress in realtime. 
  # @param best_selling_search_request Search best selling request body 
  # @param [Hash] opts the optional parameters
  # @return [BestSellingSearchResponse]
  describe 'search_best_selling test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for search_by_image
  # Searches AliExpress by image in realtime. 
  # @param image_search_request The image search request body 
  # @param [Hash] opts the optional parameters
  # @return [ImageSearchResponse]
  describe 'search_by_image test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for upload_image_by_url
  # Uploads an image to AliExpress to allow it to be used in the image search endpoint 
  # @param upload_image_by_url_request The upload image by url request body 
  # @param [Hash] opts the optional parameters
  # @return [UploadImageResponse]
  describe 'upload_image_by_url test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
