=begin
#AllQ

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.2

=end

require 'uri'

module Allq
  class AdminApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Drain tube and delete it
    # Drain Server
    # @param server_id Server URL or ID
    # @param [Hash] opts the optional parameters
    # @return [BasicResponse]
    def drain_server(server_id, opts = {})
      data, _status_code, _headers = drain_server_with_http_info(server_id, opts)
      data
    end

    # Drain tube and delete it
    # Drain Server
    # @param server_id Server URL or ID
    # @param [Hash] opts the optional parameters
    # @return [Array<(BasicResponse, Fixnum, Hash)>] BasicResponse data, response status code and response headers
    def drain_server_with_http_info(server_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AdminApi.drain_server ...'
      end
      # verify the required parameter 'server_id' is set
      if @api_client.config.client_side_validation && server_id.nil?
        fail ArgumentError, "Missing the required parameter 'server_id' when calling AdminApi.drain_server"
      end
      # resource path
      local_var_path = '/drain'

      # query parameters
      query_params = {}
      query_params[:'server_id'] = server_id

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:PUT, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'BasicResponse')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AdminApi#drain_server\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
    # Stats
    # Get Stats
    # @param [Hash] opts the optional parameters
    # @return [Array<StatsResults>]
    def stats_get(opts = {})
      data, _status_code, _headers = stats_get_with_http_info(opts)
      data
    end

    # Stats
    # Get Stats
    # @param [Hash] opts the optional parameters
    # @return [Array<(Array<StatsResults>, Fixnum, Hash)>] Array<StatsResults> data, response status code and response headers
    def stats_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AdminApi.stats_get ...'
      end
      # resource path
      local_var_path = '/stats'

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<StatsResults>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AdminApi#stats_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
    # Reset Server Urls
    # Change server URLs
    # @param server_urls Comma Separated List URL String
    # @param [Hash] opts the optional parameters
    # @return [BasicResponse]
    def update_servers_put(server_urls, opts = {})
      data, _status_code, _headers = update_servers_put_with_http_info(server_urls, opts)
      data
    end

    # Reset Server Urls
    # Change server URLs
    # @param server_urls Comma Separated List URL String
    # @param [Hash] opts the optional parameters
    # @return [Array<(BasicResponse, Fixnum, Hash)>] BasicResponse data, response status code and response headers
    def update_servers_put_with_http_info(server_urls, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AdminApi.update_servers_put ...'
      end
      # verify the required parameter 'server_urls' is set
      if @api_client.config.client_side_validation && server_urls.nil?
        fail ArgumentError, "Missing the required parameter 'server_urls' when calling AdminApi.update_servers_put"
      end
      # resource path
      local_var_path = '/update_servers'

      # query parameters
      query_params = {}
      query_params[:'server_urls'] = server_urls

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:PUT, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'BasicResponse')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AdminApi#update_servers_put\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
