# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/module/server_info/server_info.proto

require 'google/protobuf'


descriptor_data = "\n-internal/module/server_info/server_info.proto\x12\x18gitlab.agent.server_info\"@\n\nServerInfo\x12\x18\n\x07version\x18\x01 \x01(\tR\x07version\x12\x18\n\x07git_ref\x18\x02 \x01(\tR\x07git_refBXZVgitlab.com/gitlab-org/cluster-integration/gitlab-agent/v17/internal/module/server_infob\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Gitlab
  module Agent
    module ServerInfo
      ServerInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitlab.agent.server_info.ServerInfo").msgclass
    end
  end
end
