# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pkg/event/event.proto

require 'google/protobuf'

require 'buf/validate/validate_pb'
require 'google/protobuf/any_pb'
require 'google/protobuf/timestamp_pb'


descriptor_data = "\n\x15pkg/event/event.proto\x12\x12gitlab.agent.event\x1a\x1b\x62uf/validate/validate.proto\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"M\n\x0cGitPushEvent\x12=\n\x07project\x18\x01 \x01(\x0b\x32\x1b.gitlab.agent.event.ProjectB\x06\xbaH\x03\xc8\x01\x01R\x07project\"H\n\x07Project\x12\x17\n\x02id\x18\x01 \x01(\x03\x42\x07\xbaH\x04\"\x02 \x00R\x02id\x12$\n\tfull_path\x18\x02 \x01(\tB\x07\xbaH\x04r\x02 \x01R\x08\x66ullPath\"\xd1\x05\n\nCloudEvent\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n\x06source\x18\x02 \x01(\tR\x06source\x12!\n\x0cspec_version\x18\x03 \x01(\tR\x0bspecVersion\x12\x12\n\x04type\x18\x04 \x01(\tR\x04type\x12N\n\nattributes\x18\x05 \x03(\x0b\x32..gitlab.agent.event.CloudEvent.AttributesEntryR\nattributes\x12!\n\x0b\x62inary_data\x18\x06 \x01(\x0cH\x00R\nbinaryData\x12\x1d\n\ttext_data\x18\x07 \x01(\tH\x00R\x08textData\x12\x35\n\nproto_data\x18\x08 \x01(\x0b\x32\x14.google.protobuf.AnyH\x00R\tprotoData\x1av\n\x0f\x41ttributesEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12M\n\x05value\x18\x02 \x01(\x0b\x32\x37.gitlab.agent.event.CloudEvent.CloudEventAttributeValueR\x05value:\x02\x38\x01\x1a\x9a\x02\n\x18\x43loudEventAttributeValue\x12\x1f\n\nce_boolean\x18\x01 \x01(\x08H\x00R\tceBoolean\x12\x1f\n\nce_integer\x18\x02 \x01(\x05H\x00R\tceInteger\x12\x1d\n\tce_string\x18\x03 \x01(\tH\x00R\x08\x63\x65String\x12\x1b\n\x08\x63\x65_bytes\x18\x04 \x01(\x0cH\x00R\x07\x63\x65\x42ytes\x12\x17\n\x06\x63\x65_uri\x18\x05 \x01(\tH\x00R\x05\x63\x65Uri\x12\x1e\n\nce_uri_ref\x18\x06 \x01(\tH\x00R\x08\x63\x65UriRef\x12?\n\x0c\x63\x65_timestamp\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00R\x0b\x63\x65TimestampB\x06\n\x04\x61ttrB\x06\n\x04\x64\x61taBFZDgitlab.com/gitlab-org/cluster-integration/gitlab-agent/v17/pkg/eventb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Gitlab
  module Agent
    module Event
      GitPushEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitlab.agent.event.GitPushEvent").msgclass
      Project = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitlab.agent.event.Project").msgclass
      CloudEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitlab.agent.event.CloudEvent").msgclass
      CloudEvent::CloudEventAttributeValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitlab.agent.event.CloudEvent.CloudEventAttributeValue").msgclass
    end
  end
end
