require 'internal/module/server_info/rpc/rpc_services_pb'
require 'internal/module/agent_tracker/rpc/rpc_services_pb'
require 'internal/module/configuration_project/rpc/rpc_services_pb'
require 'internal/module/autoflow/rpc/rpc_services_pb'
require 'internal/module/notifications/rpc/rpc_services_pb'
