# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/module/agent_tracker/rpc/rpc.proto

require 'google/protobuf'

require 'internal/module/agent_tracker/agent_tracker_pb'


descriptor_data = "\n+internal/module/agent_tracker/rpc/rpc.proto\x12\x1egitlab.agent.agent_tracker.rpc\x1a\x31internal/module/agent_tracker/agent_tracker.proto\"H\n%GetConnectedAgentsByProjectIDsRequest\x12\x1f\n\x0bproject_ids\x18\x01 \x03(\x03R\nprojectIds\"B\n#GetConnectedAgentsByAgentIDsRequest\x12\x1b\n\tagent_ids\x18\x01 \x03(\x03R\x08\x61gentIds\"p\n&GetConnectedAgentsByProjectIDsResponse\x12\x46\n\x06\x61gents\x18\x01 \x03(\x0b\x32..gitlab.agent.agent_tracker.ConnectedAgentInfoR\x06\x61gents\"n\n$GetConnectedAgentsByAgentIDsResponse\x12\x46\n\x06\x61gents\x18\x01 \x03(\x0b\x32..gitlab.agent.agent_tracker.ConnectedAgentInfoR\x06\x61gents\"#\n!CountAgentsByAgentVersionsRequest\"\xe4\x01\n\"CountAgentsByAgentVersionsResponse\x12|\n\x0e\x61gent_versions\x18\x01 \x03(\x0b\x32U.gitlab.agent.agent_tracker.rpc.CountAgentsByAgentVersionsResponse.AgentVersionsEntryR\ragentVersions\x1a@\n\x12\x41gentVersionsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\x03R\x05value:\x02\x38\x01\x32\x98\x04\n\x0c\x41gentTracker\x12\xb1\x01\n\x1eGetConnectedAgentsByProjectIDs\x12\x45.gitlab.agent.agent_tracker.rpc.GetConnectedAgentsByProjectIDsRequest\x1a\x46.gitlab.agent.agent_tracker.rpc.GetConnectedAgentsByProjectIDsResponse\"\x00\x12\xab\x01\n\x1cGetConnectedAgentsByAgentIDs\x12\x43.gitlab.agent.agent_tracker.rpc.GetConnectedAgentsByAgentIDsRequest\x1a\x44.gitlab.agent.agent_tracker.rpc.GetConnectedAgentsByAgentIDsResponse\"\x00\x12\xa5\x01\n\x1a\x43ountAgentsByAgentVersions\x12\x41.gitlab.agent.agent_tracker.rpc.CountAgentsByAgentVersionsRequest\x1a\x42.gitlab.agent.agent_tracker.rpc.CountAgentsByAgentVersionsResponse\"\x00\x42^Z\\gitlab.com/gitlab-org/cluster-integration/gitlab-agent/v17/internal/module/agent_tracker/rpcb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Gitlab
  module Agent
    module AgentTracker
      module Rpc
        GetConnectedAgentsByProjectIDsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitlab.agent.agent_tracker.rpc.GetConnectedAgentsByProjectIDsRequest").msgclass
        GetConnectedAgentsByAgentIDsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitlab.agent.agent_tracker.rpc.GetConnectedAgentsByAgentIDsRequest").msgclass
        GetConnectedAgentsByProjectIDsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitlab.agent.agent_tracker.rpc.GetConnectedAgentsByProjectIDsResponse").msgclass
        GetConnectedAgentsByAgentIDsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitlab.agent.agent_tracker.rpc.GetConnectedAgentsByAgentIDsResponse").msgclass
        CountAgentsByAgentVersionsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitlab.agent.agent_tracker.rpc.CountAgentsByAgentVersionsRequest").msgclass
        CountAgentsByAgentVersionsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitlab.agent.agent_tracker.rpc.CountAgentsByAgentVersionsResponse").msgclass
      end
    end
  end
end
