=begin
#Aliseeks API

#AliExpress product searching and product details retrieval API. 

OpenAPI spec version: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'date'

module AliseeksApi
  class ProductRequestComponent
    
    SHIPPING = 'shipping'.freeze
    HTML_DESCRIPTION = 'html_description'.freeze
    VARIATIONS = 'variations'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ProductRequestComponent.constants.select { |c| ProductRequestComponent::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ProductRequestComponent" if constantValues.empty?
      value
    end
  end
end
