=begin
#Aliseeks API

#AliExpress product searching and product details retrieval API. 

OpenAPI spec version: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

# Common files
require 'aliseeks_api/api_client'
require 'aliseeks_api/api_error'
require 'aliseeks_api/version'
require 'aliseeks_api/configuration'

# Models
require 'aliseeks_api/models/amount'
require 'aliseeks_api/models/best_selling_search_item'
require 'aliseeks_api/models/best_selling_search_request'
require 'aliseeks_api/models/best_selling_search_response'
require 'aliseeks_api/models/double_range'
require 'aliseeks_api/models/image_search_category'
require 'aliseeks_api/models/image_search_item'
require 'aliseeks_api/models/image_search_request'
require 'aliseeks_api/models/image_search_response'
require 'aliseeks_api/models/integer_range'
require 'aliseeks_api/models/non_realtime_currency'
require 'aliseeks_api/models/price_range'
require 'aliseeks_api/models/price_summary'
require 'aliseeks_api/models/product'
require 'aliseeks_api/models/product_attribute'
require 'aliseeks_api/models/product_bulk_option'
require 'aliseeks_api/models/product_detail'
require 'aliseeks_api/models/product_details_request'
require 'aliseeks_api/models/product_html_description'
require 'aliseeks_api/models/product_html_description_request'
require 'aliseeks_api/models/product_price_option'
require 'aliseeks_api/models/product_promotion'
require 'aliseeks_api/models/product_property_variation_identifier'
require 'aliseeks_api/models/product_request'
require 'aliseeks_api/models/product_request_component'
require 'aliseeks_api/models/product_review'
require 'aliseeks_api/models/product_reviews'
require 'aliseeks_api/models/product_reviews_request'
require 'aliseeks_api/models/product_seller'
require 'aliseeks_api/models/product_shipping'
require 'aliseeks_api/models/product_shipping_options'
require 'aliseeks_api/models/product_shipping_request'
require 'aliseeks_api/models/product_sku'
require 'aliseeks_api/models/product_skus'
require 'aliseeks_api/models/product_skus_request'
require 'aliseeks_api/models/promotion_option'
require 'aliseeks_api/models/realtime_currency'
require 'aliseeks_api/models/realtime_search_aggregation'
require 'aliseeks_api/models/realtime_search_item'
require 'aliseeks_api/models/realtime_search_request'
require 'aliseeks_api/models/realtime_search_response'
require 'aliseeks_api/models/search_aggregation'
require 'aliseeks_api/models/search_item'
require 'aliseeks_api/models/search_item_freight'
require 'aliseeks_api/models/search_item_freight_type'
require 'aliseeks_api/models/search_item_seller'
require 'aliseeks_api/models/search_price_option'
require 'aliseeks_api/models/search_request'
require 'aliseeks_api/models/search_response'
require 'aliseeks_api/models/sku_price_option'
require 'aliseeks_api/models/sku_price_option_property'
require 'aliseeks_api/models/sku_property'
require 'aliseeks_api/models/sku_property_value'
require 'aliseeks_api/models/string_range'
require 'aliseeks_api/models/time_duration'
require 'aliseeks_api/models/trade_information'
require 'aliseeks_api/models/upload_image_by_url_request'
require 'aliseeks_api/models/upload_image_response'
require 'aliseeks_api/models/web_error'

# APIs
require 'aliseeks_api/api/products_api'
require 'aliseeks_api/api/search_api'

module AliseeksApi
  class << self
    # Customize default settings for the SDK using block.
    #   AliseeksApi.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
