inherit_gem:
  gitlab-styles:
    - rubocop-default.yml

CodeReuse/ActiveRecord:
  Exclude:
    - spec/**/*.rb

RSpec/FilePath:
  Exclude:
    - spec/gitlab-sdk/version_spec.rb
  CustomTransform:
    GitlabSDK: gitlab-sdk

RSpec/MultipleMemoizedHelpers:
  Max: 10

Naming/FileName:
  Exclude:
    - lib/gitlab-sdk.rb

RSpec/MultipleMemoizedHelpers:
  Max: 25
  AllowSubject: true
