# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/module/agent_tracker/agent_tracker.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'pkg/entity/entity_pb'
require 'buf/validate/validate_pb'


descriptor_data = "\n1internal/module/agent_tracker/agent_tracker.proto\x12\x1agitlab.agent.agent_tracker\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17pkg/entity/entity.proto\x1a\x1b\x62uf/validate/validate.proto\"\x88\x02\n\x12\x43onnectedAgentInfo\x12\x46\n\nagent_meta\x18\x01 \x01(\x0b\x32\x1e.gitlab.agent.entity.AgentMetaB\x06\xbaH\x03\xc8\x01\x01R\nagent_meta\x12H\n\x0c\x63onnected_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x08\xbaH\x05\xb2\x01\x02*\x00R\x0c\x63onnected_at\x12$\n\rconnection_id\x18\x03 \x01(\x03R\rconnection_id\x12\x1a\n\x08\x61gent_id\x18\x04 \x01(\x03R\x08\x61gent_id\x12\x1e\n\nproject_id\x18\x05 \x01(\x03R\nproject_id\"\xb7\x01\n\x13\x44isconnectAgentInfo\x12>\n\nagent_meta\x18\x01 \x01(\x0b\x32\x1e.gitlab.agent.entity.AgentMetaR\nagent_meta\x12$\n\rconnection_id\x18\x02 \x01(\x03R\rconnection_id\x12\x1a\n\x08\x61gent_id\x18\x03 \x01(\x03R\x08\x61gent_id\x12\x1e\n\nproject_id\x18\x04 \x01(\x03R\nproject_id\"B\n\x0c\x41gentPodInfo\x12\x1a\n\x08\x61gent_id\x18\x01 \x01(\x03R\x08\x61gent_id\x12\x16\n\x06pod_id\x18\x02 \x01(\x03R\x06pod_idBZZXgitlab.com/gitlab-org/cluster-integration/gitlab-agent/v17/internal/module/agent_trackerb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Gitlab
  module Agent
    module AgentTracker
      ConnectedAgentInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitlab.agent.agent_tracker.ConnectedAgentInfo").msgclass
      DisconnectAgentInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitlab.agent.agent_tracker.DisconnectAgentInfo").msgclass
      AgentPodInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitlab.agent.agent_tracker.AgentPodInfo").msgclass
    end
  end
end
