=begin
#Aliseeks API

#AliExpress product searching and product details retrieval API. 

OpenAPI spec version: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'spec_helper'
require 'json'

# Unit tests for AliseeksApi::ProductsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ProductsApi' do
  before do
    # run before each test
    @instance = AliseeksApi::ProductsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProductsApi' do
    it 'should create an instance of ProductsApi' do
      expect(@instance).to be_instance_of(AliseeksApi::ProductsApi)
    end
  end

  # unit tests for get_product
  # Get products details as an aggregated request from AliExpress in realtime. 
  # @param [Hash] opts the optional parameters
  # @option opts [ProductRequest] :product_request The request body of get product 
  # @return [Product]
  describe 'get_product test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_product_details
  # Gets product details from AliExpress in realtime. 
  # @param product_details_request The request body to get product details 
  # @param [Hash] opts the optional parameters
  # @return [ProductDetail]
  describe 'get_product_details test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_product_html_description
  # Get product HTML description from AliExpress in realtime. 
  # @param product_html_description_request The request body to get product html description 
  # @param [Hash] opts the optional parameters
  # @return [ProductHtmlDescription]
  describe 'get_product_html_description test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_product_reviews
  # Get product reviews from AliExpress in realtime 
  # @param product_reviews_request The request body to get product reviews 
  # @param [Hash] opts the optional parameters
  # @return [ProductReviews]
  describe 'get_product_reviews test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_product_shipping
  # Gets product shipping information AliExpress in realtime. 
  # @param product_shipping_request The request body to get product shipping 
  # @param [Hash] opts the optional parameters
  # @return [ProductShipping]
  describe 'get_product_shipping test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_product_skus
  # Gets product skus / variation information from AliExpress in realtime. 
  # @param product_skus_request The request body to get product skus / variations 
  # @param [Hash] opts the optional parameters
  # @return [ProductSkus]
  describe 'get_product_skus test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
