# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/module/notifications/rpc/rpc.proto

require 'google/protobuf'

require 'buf/validate/validate_pb'
require 'pkg/event/event_pb'


descriptor_data = "\n+internal/module/notifications/rpc/rpc.proto\x12\x1egitlab.agent.notifications.rpc\x1a\x1b\x62uf/validate/validate.proto\x1a\x15pkg/event/event.proto\"U\n\x13GitPushEventRequest\x12>\n\x05\x65vent\x18\x01 \x01(\x0b\x32 .gitlab.agent.event.GitPushEventB\x06\xbaH\x03\xc8\x01\x01R\x05\x65vent\"\x16\n\x14GitPushEventResponse2\x8c\x01\n\rNotifications\x12{\n\x0cGitPushEvent\x12\x33.gitlab.agent.notifications.rpc.GitPushEventRequest\x1a\x34.gitlab.agent.notifications.rpc.GitPushEventResponse\"\x00\x42^Z\\gitlab.com/gitlab-org/cluster-integration/gitlab-agent/v17/internal/module/notifications/rpcb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Gitlab
  module Agent
    module Notifications
      module Rpc
        GitPushEventRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitlab.agent.notifications.rpc.GitPushEventRequest").msgclass
        GitPushEventResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitlab.agent.notifications.rpc.GitPushEventResponse").msgclass
      end
    end
  end
end
