=begin
#AllQ

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.2

=end

# Common files
require 'allq_client/api_client'
require 'allq_client/api_error'
require 'allq_client/version'
require 'allq_client/configuration'

# Models
require 'allq_client/models/basic_payload'
require 'allq_client/models/basic_response'
require 'allq_client/models/job_ref'
require 'allq_client/models/job_response'
require 'allq_client/models/multiple_job_response'
require 'allq_client/models/new_job'
require 'allq_client/models/new_parent_job'
require 'allq_client/models/stats_info'
require 'allq_client/models/stats_results'
require 'allq_client/models/stats_tube'
require 'allq_client/models/throttle'
require 'allq_client/models/tube_ref'

# APIs
require 'allq_client/api/actions_api'
require 'allq_client/api/admin_api'

module Allq
  class << self
    # Customize default settings for the SDK using block.
    #   Allq.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
