# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'lint_pb'


descriptor_data = "\n\x0einternal.proto\x12\x06gitaly\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\nlint.proto\".\n\x10WalkReposRequest\x12\x1a\n\x0cstorage_name\x18\x01 \x01(\tB\x04\x88\xc6,\x01\"a\n\x11WalkReposResponse\x12\x15\n\rrelative_path\x18\x01 \x01(\t\x12\x35\n\x11modification_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2^\n\x0eInternalGitaly\x12L\n\tWalkRepos\x12\x18.gitaly.WalkReposRequest\x1a\x19.gitaly.WalkReposResponse\"\x08\xfa\x97(\x04\x08\x02\x10\x02\x30\x01\x42\x34Z2gitlab.com/gitlab-org/gitaly/v16/proto/go/gitalypbb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
    ["google.protobuf.Timestamp", "google/protobuf/timestamp.proto"],
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Gitaly
  WalkReposRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.WalkReposRequest").msgclass
  WalkReposResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.WalkReposResponse").msgclass
end
