# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packfile.proto

require 'google/protobuf'


descriptor_data = "\n\x0epackfile.proto\x12\x06gitaly\"\xa4\x01\n\x1dPackfileNegotiationStatistics\x12\x14\n\x0cpayload_size\x18\x01 \x01(\x03\x12\x0f\n\x07packets\x18\x02 \x01(\x03\x12\x0c\n\x04\x63\x61ps\x18\x03 \x03(\t\x12\r\n\x05wants\x18\x04 \x01(\x03\x12\r\n\x05haves\x18\x05 \x01(\x03\x12\x10\n\x08shallows\x18\x06 \x01(\x03\x12\x0e\n\x06\x64\x65\x65pen\x18\x07 \x01(\t\x12\x0e\n\x06\x66ilter\x18\x08 \x01(\tB4Z2gitlab.com/gitlab-org/gitaly/v16/proto/go/gitalypbb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Gitaly
  PackfileNegotiationStatistics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.PackfileNegotiationStatistics").msgclass
end
