# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remote.proto

require 'google/protobuf'

require 'lint_pb'
require 'shared_pb'


descriptor_data = "\n\x0cremote.proto\x12\x06gitaly\x1a\nlint.proto\x1a\x0cshared.proto\"\xdb\x02\n\x19UpdateRemoteMirrorRequest\x12,\n\nrepository\x18\x01 \x01(\x0b\x32\x12.gitaly.RepositoryB\x04\x98\xc6,\x01\x12\x38\n\x06remote\x18\x07 \x01(\x0b\x32(.gitaly.UpdateRemoteMirrorRequest.Remote\x12\x1e\n\x16only_branches_matching\x18\x03 \x03(\x0c\x12\x0f\n\x07ssh_key\x18\x04 \x01(\t\x12\x13\n\x0bknown_hosts\x18\x05 \x01(\t\x12\x1b\n\x13keep_divergent_refs\x18\x06 \x01(\x08\x1a\x63\n\x06Remote\x12\x0b\n\x03url\x18\x01 \x01(\t\x12!\n\x19http_authorization_header\x18\x02 \x01(\t\x12\x18\n\x10resolved_address\x18\x04 \x01(\tJ\x04\x08\x03\x10\x04R\thttp_hostJ\x04\x08\x02\x10\x03R\x08ref_name\"4\n\x1aUpdateRemoteMirrorResponse\x12\x16\n\x0e\x64ivergent_refs\x18\x01 \x03(\x0c\"I\n\x1b\x46indRemoteRepositoryRequest\x12\x0e\n\x06remote\x18\x01 \x01(\t\x12\x1a\n\x0cstorage_name\x18\x02 \x01(\tB\x04\x88\xc6,\x01\".\n\x1c\x46indRemoteRepositoryResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\"\xb8\x01\n\x18\x46indRemoteRootRefRequest\x12,\n\nrepository\x18\x01 \x01(\x0b\x32\x12.gitaly.RepositoryB\x04\x98\xc6,\x01\x12\x12\n\nremote_url\x18\x03 \x01(\t\x12!\n\x19http_authorization_header\x18\x04 \x01(\t\x12\x18\n\x10resolved_address\x18\x06 \x01(\tJ\x04\x08\x02\x10\x03J\x04\x08\x05\x10\x06R\x06remoteR\thttp_host\"(\n\x19\x46indRemoteRootRefResponse\x12\x0b\n\x03ref\x18\x01 \x01(\t2\xc5\x02\n\rRemoteService\x12\x65\n\x12UpdateRemoteMirror\x12!.gitaly.UpdateRemoteMirrorRequest\x1a\".gitaly.UpdateRemoteMirrorResponse\"\x06\xfa\x97(\x02\x08\x02(\x01\x12k\n\x14\x46indRemoteRepository\x12#.gitaly.FindRemoteRepositoryRequest\x1a$.gitaly.FindRemoteRepositoryResponse\"\x08\xfa\x97(\x04\x08\x02\x10\x02\x12`\n\x11\x46indRemoteRootRef\x12 .gitaly.FindRemoteRootRefRequest\x1a!.gitaly.FindRemoteRootRefResponse\"\x06\xfa\x97(\x02\x08\x02\x42\x34Z2gitlab.com/gitlab-org/gitaly/v16/proto/go/gitalypbb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
    ["gitaly.Repository", "shared.proto"],
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Gitaly
  UpdateRemoteMirrorRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.UpdateRemoteMirrorRequest").msgclass
  UpdateRemoteMirrorRequest::Remote = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.UpdateRemoteMirrorRequest.Remote").msgclass
  UpdateRemoteMirrorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.UpdateRemoteMirrorResponse").msgclass
  FindRemoteRepositoryRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.FindRemoteRepositoryRequest").msgclass
  FindRemoteRepositoryResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.FindRemoteRepositoryResponse").msgclass
  FindRemoteRootRefRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.FindRemoteRootRefRequest").msgclass
  FindRemoteRootRefResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.FindRemoteRootRefResponse").msgclass
end
