# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: server.proto for package 'gitaly'

require 'grpc'
require 'server_pb'

module Gitaly
  module ServerService
    # ServerService is a service that provides information about a Gitaly server.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'gitaly.ServerService'

      # ServerInfo ...
      rpc :ServerInfo, ::Gitaly::ServerInfoRequest, ::Gitaly::ServerInfoResponse
      # DiskStatistics ...
      rpc :DiskStatistics, ::Gitaly::DiskStatisticsRequest, ::Gitaly::DiskStatisticsResponse
      # ReadinessCheck runs the set of the checks to make sure service is in operational state.
      rpc :ReadinessCheck, ::Gitaly::ReadinessCheckRequest, ::Gitaly::ReadinessCheckResponse
      # ServerSignature returns the contents of the public key used to sign
      # commits made through the GitLab UI or Web IDE.
      # See https://docs.gitlab.com/ee/user/project/repository/signed_commits/#verify-commits-made-in-the-web-ui
      # for more information.
      rpc :ServerSignature, ::Gitaly::ServerSignatureRequest, ::Gitaly::ServerSignatureResponse
    end

    Stub = Service.rpc_stub_class
  end
end
