# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: ssh.proto for package 'gitaly'

require 'grpc'
require 'ssh_pb'

module Gitaly
  module SSHService
    # SSHService is a service that provides RPCs required for SSH-based Git clones.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'gitaly.SSHService'

      # SSHUploadPackWithSidechannel is an RPC to forward git-upload-pack(1) to Gitaly for SSH
      # sessions, via sidechannels. Sidechannel connections sidestep gRPC Protobuf message overhead and
      # allow higher throughput of bulk data transfers. The stdin, stdout, and stderr for the
      # git-upload-pack(1) are streamed through the sidechannel connection.
      rpc :SSHUploadPackWithSidechannel, ::Gitaly::SSHUploadPackWithSidechannelRequest, ::Gitaly::SSHUploadPackWithSidechannelResponse
      # SSHReceivePack is an RPC to forward git-receive-pack(1) to Gitaly for SSH sessions. The RPC uses
      # bidirectional streaming so the client can stream stdin and the server can stream stdout and
      # stderr for git-receive-pack(1).
      rpc :SSHReceivePack, stream(::Gitaly::SSHReceivePackRequest), stream(::Gitaly::SSHReceivePackResponse)
      # SSHUploadArchive is an RPC to forward git-upload-archive(1) to Gitaly for SSH sessions. The RPC
      # uses bidirectional streaming so the client can stream stdin and the server can stream stdout
      # and stderr for git-upload-archive(1).
      rpc :SSHUploadArchive, stream(::Gitaly::SSHUploadArchiveRequest), stream(::Gitaly::SSHUploadArchiveResponse)
    end

    Stub = Service.rpc_stub_class
  end
end
