# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto

require 'google/protobuf'

require 'lint_pb'
require 'shared_pb'


descriptor_data = "\n\x11transaction.proto\x12\x06gitaly\x1a\nlint.proto\x1a\x0cshared.proto\"\x9e\x02\n\x16VoteTransactionRequest\x12,\n\nrepository\x18\x01 \x01(\x0b\x32\x12.gitaly.RepositoryB\x04\x98\xc6,\x01\x12\x16\n\x0etransaction_id\x18\x02 \x01(\x04\x12\x0c\n\x04node\x18\x03 \x01(\t\x12\x1e\n\x16reference_updates_hash\x18\x04 \x01(\x0c\x12\x33\n\x05phase\x18\x05 \x01(\x0e\x32$.gitaly.VoteTransactionRequest.Phase\"[\n\x05Phase\x12\x11\n\rUNKNOWN_PHASE\x10\x00\x12\x12\n\x0ePREPARED_PHASE\x10\x01\x12\x13\n\x0f\x43OMMITTED_PHASE\x10\x02\x12\x16\n\x12SYNCHRONIZED_PHASE\x10\x03\"\x8f\x01\n\x17VoteTransactionResponse\x12?\n\x05state\x18\x01 \x01(\x0e\x32\x30.gitaly.VoteTransactionResponse.TransactionState\"3\n\x10TransactionState\x12\n\n\x06\x43OMMIT\x10\x00\x12\t\n\x05\x41\x42ORT\x10\x01\x12\x08\n\x04STOP\x10\x02\"^\n\x16StopTransactionRequest\x12,\n\nrepository\x18\x01 \x01(\x0b\x32\x12.gitaly.RepositoryB\x04\x98\xc6,\x01\x12\x16\n\x0etransaction_id\x18\x02 \x01(\x04\"\x19\n\x17StopTransactionResponse2\xbe\x01\n\x0eRefTransaction\x12R\n\x0fVoteTransaction\x12\x1e.gitaly.VoteTransactionRequest\x1a\x1f.gitaly.VoteTransactionResponse\x12R\n\x0fStopTransaction\x12\x1e.gitaly.StopTransactionRequest\x1a\x1f.gitaly.StopTransactionResponse\x1a\x04\xf0\x97(\x01\x42\x34Z2gitlab.com/gitlab-org/gitaly/v16/proto/go/gitalypbb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
    ["gitaly.Repository", "shared.proto"],
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Gitaly
  VoteTransactionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.VoteTransactionRequest").msgclass
  VoteTransactionRequest::Phase = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.VoteTransactionRequest.Phase").enummodule
  VoteTransactionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.VoteTransactionResponse").msgclass
  VoteTransactionResponse::TransactionState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.VoteTransactionResponse.TransactionState").enummodule
  StopTransactionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.StopTransactionRequest").msgclass
  StopTransactionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.StopTransactionResponse").msgclass
end
