---
engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
  rubocop-gitlab:
    enabled: true
ratings:
  paths:
    - Gemfile.lock
    - "**.rb"
exclude_paths:
  - spec/
  - vendor/
  - tmp/
