# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buf/validate/validate.proto

require 'google/protobuf'


descriptor_data = "\n\x1b\x62uf/validate/validate.proto\x12\x0c\x62uf.validateb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Buf
  module Validate
  end
end
