=begin
#Aliseeks API

#AliExpress product searching and product details retrieval API. 

OpenAPI spec version: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AliseeksApi::RealtimeSearchRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RealtimeSearchRequest' do
  before do
    # run before each test
    @instance = AliseeksApi::RealtimeSearchRequest.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RealtimeSearchRequest' do
    it 'should create an instance of RealtimeSearchRequest' do
      expect(@instance).to be_instance_of(AliseeksApi::RealtimeSearchRequest)
    end
  end
  describe 'test attribute "category"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "text"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "price_range"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "ship_to_country"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "ship_from_country"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "sort"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["BEST_MATCH", "HIGHEST_PRICE", "LOWEST_PRICE", "NUMBER_OF_ORDERS", "SELLER_RATING", "NEWEST_TO_OLDEST"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.sort = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "skip"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
