BRIGHT_PROJECT_URL              = 'git@gitlab.development.ice.local:bright-ios/bright.git'
BRIGHT_BRANCH                   = 'CoreApplicationDelegate'
BRIGHT_REQUIRED                 = [ "CoreProductModules","ParisHilton" ]
BRIGHT_COMMON_RESOURCES         = 'WhiteLabel/WhiteLabel/Resources/*'
BRIGHT_DEFAULT_ASSETCATALOG     = 'WhiteLabel/Bright/Resources/Assets.xcassets'
BRIGHT_REVISION_SCRIPT          = 'WhiteLabel/Generate-Revision.sh'

module Pod
  class Command
    class IceGenerate < Command

      self.summary = "Generate a new IceMobile BrightShopper Project"
      self.arguments = 'NAME','PREFIX'

      def initialize(argv)
        @name = argv.shift_argument
        @prefix = argv.shift_argument
        ENV['CP_PROJECT_NAME'] = @name
        super
      end

      def validate!
        super
        help! "Usage: ice-generate <PROJECT_NAME> <PROJECT_PREFIX>" unless @name && @prefix
      end
     
      def run
          new_project(@name)
      end

      public

      def new_project(name)
        if File.directory?("#{name}")
          UI.puts"Fatal: Directory #{name} already exists. Please delete it and run again.".red
          return
        end

        FileUtils.mkdir_p("#{@name}")
        run_git_command("clone -b #{BRIGHT_BRANCH} #{BRIGHT_PROJECT_URL} ../#{@name}")

        create_project_files
        create_xcode_project
        copy_resources
        remove_unnecessary_folders

        run_pod_command('install')

        run_git_command("add -A")
        run_git_command(%q(commit -m "Autogenerated project with cocoapods-icemobile-plugin"))
        run_git_command("remote rm origin")
      end

      def remove_unnecessary_folders
        Dir.foreach("./#{@name}") do |item|
          next if item == '.' or item == '..' or item.start_with?".git" or item.start_with?"Pod" or item.start_with?"README.md" or BRIGHT_REQUIRED.include?(item) or item.start_with?"#{@name}" 
            UI.puts "Removing #{item}".green
            FileUtils.rm_rf("./#{@name}/#{item}")
        end
      end

      def create_project_files
        #Create Directories
        FileUtils.mkdir_p("#{@name}/#{@name}")
        dirs = ["Supporting Files", "Skinners", "Resources", "Scripts"]
        dirs.each { |dir| FileUtils.mkdir_p("#{@name}/#{@name}//#{dir}/") }
        FileUtils.mkdir_p("#{@name}/#{@name}/Resources/Common/")
      
        #Create Root Files
        Dir.chdir "#{@name}" do
          File.delete(".gitignore") if File.exist?(".gitignore")
          Pod::Helper::Gitignore.new(@name,@prefix).file
          Pod::Helper::Podfile.new(@name,@prefix).file
          Pod::Helper::Readme.new(@name,@prefix).file
        end

        #Create Bootstrap Delegates
        Dir.chdir "#{@name}/#{@name}" do
          Pod::Helper::BootstrapDelegateH.new(@name,@prefix).file
          Pod::Helper::BootstrapDelegateM.new(@name,@prefix).file
        end

        #Create Supporting Files
        Dir.chdir "#{@name}/#{@name}/Supporting Files" do
          Pod::Helper::InfoPlist.new(@name,@prefix).file
          Pod::Helper::MainM.new(@name,@prefix).file
          Pod::Helper::PrefixHeader.new(@name,@prefix).file
        end

        #Create SidebarContainerViewControllerSkinner
        Dir.chdir "#{@name}/#{@name}/Skinners" do
          Pod::Helper::SidebarContainerViewControllerSkinnerH.new(@name,@prefix).file
          Pod::Helper::SidebarContainerViewControllerSkinnerM.new(@name,@prefix).file
        end

      end

      def copy_resources
        Dir.chdir(@name) do
            UI.puts "Copying Resources from WhiteLabel".green
            system("cp -r #{BRIGHT_COMMON_RESOURCES} #{@name}/Resources/Common/")
            system("cp -r #{BRIGHT_DEFAULT_ASSETCATALOG} #{@name}/Resources/")
            system("cp #{BRIGHT_REVISION_SCRIPT} #{@name}/Scripts")
        end
      end

      def create_xcode_project
        UI.puts "Creating #{@name}.xcodeproj"
        builder = Helper::ProjectBuilder.new(@name,@prefix)
        project = builder.build_project
      end

      def run_git_command(command)
        Dir.chdir(@name) do
            UI.puts "run git #{command}".green
            system("git #{command}")
        end
      end

      def run_pod_command(command)
        Dir.chdir(@name) do
            UI.puts "run pod #{command}".green
            system("pod #{command}")
        end
      end

      def run_bundle_command(command)
        Dir.chdir(@name) do
          _bundle_command = Gem.bin_path('bundler', 'bundle')

          require 'bundler'
          Bundler.with_clean_env do
            UI.puts "run bundle #{command}".green
            `"#{Gem.ruby}" "#{_bundle_command}" #{command}`
          end
        end
      end
    end
  end
end
