=begin
#Aliseeks API

#AliExpress product searching and product details retrieval API. 

OpenAPI spec version: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AliseeksApi::BestSellingSearchRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BestSellingSearchRequest' do
  before do
    # run before each test
    @instance = AliseeksApi::BestSellingSearchRequest.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BestSellingSearchRequest' do
    it 'should create an instance of BestSellingSearchRequest' do
      expect(@instance).to be_instance_of(AliseeksApi::BestSellingSearchRequest)
    end
  end
  describe 'test attribute "range"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["top", "weekly"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.range = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "category"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["all", "fashion", "sports", "health_beauty", "home_garden", "kids_baby", "automotive", "electronics", "men", "women"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.category = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "skip"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "locale"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "currency"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
