=begin
#Aliseeks API

#AliExpress product searching and product details retrieval API. 

OpenAPI spec version: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AliseeksApi::NonRealtimeCurrency
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'NonRealtimeCurrency' do
  before do
    # run before each test
    @instance = AliseeksApi::NonRealtimeCurrency.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of NonRealtimeCurrency' do
    it 'should create an instance of NonRealtimeCurrency' do
      expect(@instance).to be_instance_of(AliseeksApi::NonRealtimeCurrency)
    end
  end
end
