# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/module/server_info/rpc/rpc.proto for package 'gitlab.agent.server_info.rpc'

require 'grpc'
require 'internal/module/server_info/rpc/rpc_pb'

module Gitlab
  module Agent
    module ServerInfo
      module Rpc
        module ServerInfo
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'gitlab.agent.server_info.rpc.ServerInfo'

            rpc :GetServerInfo, ::Gitlab::Agent::ServerInfo::Rpc::GetServerInfoRequest, ::Gitlab::Agent::ServerInfo::Rpc::GetServerInfoResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
