=begin
Apache Felix WebConsole

Client for Apache Felix Web Console API. List bundles, configure services, etc.

OpenAPI spec version: 4.3.0
Contact: bryan.stopp@gmail.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for ApacheFelix::BundleApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BundleApi' do
  before do
    # run before each test
    @instance = ApacheFelix::BundleApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BundleApi' do
    it 'should create an instact of BundleApi' do
      expect(@instance).to be_instance_of(ApacheFelix::BundleApi)
    end
  end

  # unit tests for info
  # Bundle Info
  # Display all information about a bundle, including properties. The returned list will contain one entry, the requested bundle. (See org.apache.felix.webconsole.internal.core.BundlesServlet.java)
  # @param bundle_id The symbolic name or id of the bundle.
  # @param [Hash] opts the optional parameters
  # @return [BundleList]
  describe 'info test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for install
  # Upload a bundle.
  # Install the provided bundle. (See org.apache.felix.webconsole.internal.core.BundlesServlet.java)
  # @param bundlefile The bundle to upload.
  # @param action The action to execute. Only allowed value is &#39;install&#39;, must be provided. Limitation of Swagger.
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :bundlestart Flag to indicate whether or not bundle should be started.
  # @option opts [Integer] :bundlestartlevel The start level of the provided bundle.
  # @option opts [BOOLEAN] :refresh_packages Flag to indicate whether or not to refresh all pacakges once installed.
  # @return [nil]
  describe 'install test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list
  # List bundles
  # List all the bundles in the Felix system. Properties for a bundle will not be populated. (See org.apache.felix.webconsole.internal.core.BundlesServlet.java)
  # @param [Hash] opts the optional parameters
  # @return [BundleList]
  describe 'list test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for modify
  # Modify bundles operation.
  # Take action on a bundle; start, stop, update, refresh, uninstall. (See org.apache.felix.webconsole.internal.core.BundlesServlet.java)
  # @param bundle_symbolic_name The OSGi Symbolic name of the bundle.
  # @param action The action to execute.
  # @param [Hash] opts the optional parameters
  # @return [BundleState]
  describe 'modify test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for refresh_packages
  # Modify bundles operation.
  # Take action on all bundles - refresh packages. (See org.apache.felix.webconsole.internal.core.BundlesServlet.java)
  # @param action The action to execute. Only allowed value is &#39;refreshPackages&#39;, must be provided. Limitation of Swagger.
  # @param [Hash] opts the optional parameters
  # @return [BundleList]
  describe 'refresh_packages test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
