config:
  token: <%= ENV['CODE_STATS_TOKEN'] %>
  ci: 'CIRCLECI'
  url: <%= ENV['CODE_STATS_URL'] %>
metrics:
  rubycritic:
    name: 'RubyCritic'
    enabled: false
    minimum: 70
    upload_report: true
    report_dir: 'tmp/rubycritic'
    uploader_key: <%= ENV['CODE_STATS_S3_KEY'] %>
    uploader_secret: <%= ENV['CODE_STATS_S3_SECRET_KEY'] %>
    uploader_region: <%= ENV['CODE_STATS_S3_REGION'] %>
    uploader_bucket: <%= ENV['CODE_STATS_S3_BUCKET'] %>
  simplecov:
    name: 'SimpleCov'
    enabled: false
    minimum: 70
  slather:
    name: 'Code Coverage (Slather)'
    enabled: false
    minimum: 70
    upload_report: true
    report_dir: 'slather-output'
    uploader_key: <%= ENV['CODE_STATS_S3_KEY'] %>
    uploader_secret: <%= ENV['CODE_STATS_S3_SECRET_KEY'] %>
    uploader_region: <%= ENV['CODE_STATS_S3_REGION'] %>
    uploader_bucket: <%= ENV['CODE_STATS_S3_BUCKET'] %>
  swiftlint:
    name: 'Code Quality (Swiftlint)'
    enabled: false
    minimum: 70
    upload_report: true
    report_dir: 'swiftlint-output'
    uploader_key: <%= ENV['CODE_STATS_S3_KEY'] %>
    uploader_secret: <%= ENV['CODE_STATS_S3_SECRET_KEY'] %>
    uploader_region: <%= ENV['CODE_STATS_S3_REGION'] %>
    uploader_bucket: <%= ENV['CODE_STATS_S3_BUCKET'] %>
  tailor:
    name: 'Code Quality (Tailor)'
    enabled: false
    minimum: 70
    upload_report: true
    location: 'tailor-report.json'
    report_dir: 'tailor'
    uploader_key: <%= ENV['CODE_STATS_S3_KEY'] %>
    uploader_secret: <%= ENV['CODE_STATS_S3_SECRET_KEY'] %>
    uploader_region: <%= ENV['CODE_STATS_S3_REGION'] %>
    uploader_bucket: <%= ENV['CODE_STATS_S3_BUCKET'] %>
  escomplex:
    name: 'Js Maintainability'
    location: 'code-quality-report/stats.json'
    enabled: false
    minimum: 70
  karma_coverage:
    name: 'Code Coverage'
    location: 'test/unit/coverage/cobertura-coverage.xml'
    enabled: false
    minimum: 20
  android_jacoco:
    name: 'Test Coverage'
    location: 'app/build/reports/jacoco/testStageDebugUnitTestCoverage/testStageDebugUnitTestCoverage.xml'
    enabled: false
    minimum: 60
    build_base_url: ''
    build_report_file_url: 'jacoco'
  android_quality:
    name: 'Code Quality'
    location: 'app/build/outputs/lint-results.xml'
    enabled: false
    minimum: 70
    build_base_url: ''
    source_dir: 'app'
