require 'pathname'

require 'servers/rubycas_server'
require 'servers/spawned_rack_server'
require 'patch_castanet_7'

require 'aker/cas_cli'

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  def tmpdir
    @tmpdir ||= create_tmpdir
  end

  def create_tmpdir
    Pathname.new(File.expand_path('../tmp', __FILE__)).tap { |p| p.mkpath }
  end

  config.after(:each) do
    @tmpdir.rmtree if (@tmpdir && !ENV['KEEP_TMPDIR'])
  end

  Aker::Spec::RubycasServer.run_with_rspec_tag(:integrated, config)
  Aker::Spec::SpawnedRackServer.run_with_rspec_tag(:integrated, config,
    :name => 'proxy_callback',
    :rackup_file => File.expand_path('../servers/proxy_callback.ru.erb', __FILE__),
    :ssl => true,
    :port => '6012',
    :tmpdir => tmpdir
  );
end
