# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: analysis.proto for package 'gitaly'

require 'grpc'
require 'analysis_pb'

module Gitaly
  module AnalysisService
    # AnalysisService is a gRPC service providing RPCs that analyze objects in a repository.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'gitaly.AnalysisService'

      # CheckBlobsGenerated checks a provided set of blobs in a specified repository to determine
      # whether the file is considered generated. This RPC supports bidirectional streaming because the
      # client may specify any number of files to check across multiple request messages and the server
      # responds to each request with a separate set of response messages.
      #
      # Each provided blob in the request is validated when received. Improperly formatted requests
      # result in RPC termination and an error being returned to the client. The RPC also aborts and
      # returns an error if requests are made that list Git revisions which do not resolve to a blob
      # and/or cannot be found in the repository.
      rpc :CheckBlobsGenerated, stream(::Gitaly::CheckBlobsGeneratedRequest), stream(::Gitaly::CheckBlobsGeneratedResponse)
    end

    Stub = Service.rpc_stub_class
  end
end
