# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analysis.proto

require 'google/protobuf'

require 'lint_pb'
require 'shared_pb'


descriptor_data = "\n\x0e\x61nalysis.proto\x12\x06gitaly\x1a\nlint.proto\x1a\x0cshared.proto\"\xaa\x01\n\x1a\x43heckBlobsGeneratedRequest\x12,\n\nrepository\x18\x01 \x01(\x0b\x32\x12.gitaly.RepositoryB\x04\x98\xc6,\x01\x12\x36\n\x05\x62lobs\x18\x02 \x03(\x0b\x32\'.gitaly.CheckBlobsGeneratedRequest.Blob\x1a&\n\x04\x42lob\x12\x10\n\x08revision\x18\x01 \x01(\x0c\x12\x0c\n\x04path\x18\x02 \x01(\x0c\"\x83\x01\n\x1b\x43heckBlobsGeneratedResponse\x12\x37\n\x05\x62lobs\x18\x01 \x03(\x0b\x32(.gitaly.CheckBlobsGeneratedResponse.Blob\x1a+\n\x04\x42lob\x12\x10\n\x08revision\x18\x01 \x01(\x0c\x12\x11\n\tgenerated\x18\x02 \x01(\x08\x32}\n\x0f\x41nalysisService\x12j\n\x13\x43heckBlobsGenerated\x12\".gitaly.CheckBlobsGeneratedRequest\x1a#.gitaly.CheckBlobsGeneratedResponse\"\x06\xfa\x97(\x02\x08\x02(\x01\x30\x01\x42\x34Z2gitlab.com/gitlab-org/gitaly/v16/proto/go/gitalypbb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
    ["gitaly.Repository", "shared.proto"],
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Gitaly
  CheckBlobsGeneratedRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.CheckBlobsGeneratedRequest").msgclass
  CheckBlobsGeneratedRequest::Blob = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.CheckBlobsGeneratedRequest.Blob").msgclass
  CheckBlobsGeneratedResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.CheckBlobsGeneratedResponse").msgclass
  CheckBlobsGeneratedResponse::Blob = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.CheckBlobsGeneratedResponse.Blob").msgclass
end
