# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster.proto

require 'google/protobuf'

require 'log_pb'


descriptor_data = "\n\rcluster.proto\x12\x06gitaly\x1a\tlog.proto\"\xc6\x02\n\rRaftMessageV1\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x12\n\ncluster_id\x18\x02 \x01(\t\x12\x16\n\x0e\x61uthority_name\x18\x03 \x01(\t\x12\x14\n\x0cpartition_id\x18\x04 \x01(\x04\x12#\n\tlog_entry\x18\x05 \x01(\x0b\x32\x10.gitaly.LogEntry\x12=\n\nreferenced\x18\x06 \x01(\x0b\x32\'.gitaly.RaftMessageV1.ReferencedLogDataH\x00\x12\x35\n\x06packed\x18\x07 \x01(\x0b\x32#.gitaly.RaftMessageV1.PackedLogDataH\x00\x1a!\n\x11ReferencedLogData\x12\x0c\n\x04path\x18\x01 \x01(\x0c\x1a\x1d\n\rPackedLogData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x42\n\n\x08log_data\"=\n\x0fRaftHardStateV1\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x0c\n\x04vote\x18\x02 \x01(\x04\x12\x0e\n\x06\x63ommit\x18\x03 \x01(\x04\"w\n\x0fRaftConfStateV1\x12\x0e\n\x06voters\x18\x01 \x03(\x04\x12\x10\n\x08learners\x18\x02 \x03(\x04\x12\x17\n\x0fvoters_outgoing\x18\x03 \x03(\x04\x12\x15\n\rlearners_next\x18\x04 \x03(\x04\x12\x12\n\nauto_leave\x18\x05 \x01(\x08*S\n\x0fRaftMessageType\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\n\n\x06NORMAL\x10\x01\x12\x10\n\x0cVERIFICATION\x10\x02\x12\x11\n\rCONFIG_CHANGE\x10\x03\x42\x34Z2gitlab.com/gitlab-org/gitaly/v16/proto/go/gitalypbb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
    ["gitaly.LogEntry", "log.proto"],
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Gitaly
  RaftMessageV1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.RaftMessageV1").msgclass
  RaftMessageV1::ReferencedLogData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.RaftMessageV1.ReferencedLogData").msgclass
  RaftMessageV1::PackedLogData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.RaftMessageV1.PackedLogData").msgclass
  RaftHardStateV1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.RaftHardStateV1").msgclass
  RaftConfStateV1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.RaftConfStateV1").msgclass
  RaftMessageType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.RaftMessageType").enummodule
end
