# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: hook.proto for package 'gitaly'

require 'grpc'
require 'hook_pb'

module Gitaly
  module HookService
    # HookService is a service which provides the implementation of a subset of
    # Git hooks. These are typically invoked via the `gitaly-hooks` binary to
    # ensure that the actual hook logic is executed in the context of the server.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'gitaly.HookService'

      # PreReceiveHook ...
      rpc :PreReceiveHook, stream(::Gitaly::PreReceiveHookRequest), stream(::Gitaly::PreReceiveHookResponse)
      # PostReceiveHook ...
      rpc :PostReceiveHook, stream(::Gitaly::PostReceiveHookRequest), stream(::Gitaly::PostReceiveHookResponse)
      # UpdateHook ...
      rpc :UpdateHook, ::Gitaly::UpdateHookRequest, stream(::Gitaly::UpdateHookResponse)
      # ReferenceTransactionHook ...
      rpc :ReferenceTransactionHook, stream(::Gitaly::ReferenceTransactionHookRequest), stream(::Gitaly::ReferenceTransactionHookResponse)
      # PackObjectsHookWithSidechannel is an optimized version of PackObjectsHook that uses
      # a unix socket side channel.
      rpc :PackObjectsHookWithSidechannel, ::Gitaly::PackObjectsHookWithSidechannelRequest, ::Gitaly::PackObjectsHookWithSidechannelResponse
      # ProcReceiveHook is a hook invoked by git-receive-pack(1) [1]. This hook is responsible
      # for updating the relevant references and reporting the results back to receive-pack.
      #
      # [1]: https://git-scm.com/docs/githooks#proc-receive
      rpc :ProcReceiveHook, stream(::Gitaly::ProcReceiveHookRequest), stream(::Gitaly::ProcReceiveHookResponse)
    end

    Stub = Service.rpc_stub_class
  end
end
