# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: partition.proto

require 'google/protobuf'

require 'lint_pb'
require 'shared_pb'


descriptor_data = "\n\x0fpartition.proto\x12\x06gitaly\x1a\nlint.proto\x1a\x0cshared.proto\"P\n\x16\x42\x61\x63kupPartitionRequest\x12\x1a\n\x0cstorage_name\x18\x01 \x01(\tB\x04\x88\xc6,\x01\x12\x1a\n\x0cpartition_id\x18\x02 \x01(\tB\x04\xa8\xc6,\x01\"\x19\n\x17\x42\x61\x63kupPartitionResponse\"k\n\x15ListPartitionsRequest\x12\x1a\n\x0cstorage_name\x18\x01 \x01(\tB\x04\x88\xc6,\x01\x12\x36\n\x11pagination_params\x18\x02 \x01(\x0b\x32\x1b.gitaly.PaginationParameter\"t\n\x16ListPartitionsResponse\x12%\n\npartitions\x18\x01 \x03(\x0b\x32\x11.gitaly.Partition\x12\x33\n\x11pagination_cursor\x18\x02 \x01(\x0b\x32\x18.gitaly.PaginationCursor\"$\n\x06KVPair\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\r\n\x05value\x18\x02 \x01(\x0c\x32\xcb\x01\n\x10PartitionService\x12\\\n\x0f\x42\x61\x63kupPartition\x12\x1e.gitaly.BackupPartitionRequest\x1a\x1f.gitaly.BackupPartitionResponse\"\x08\xfa\x97(\x04\x08\x02\x10\x03\x12Y\n\x0eListPartitions\x12\x1d.gitaly.ListPartitionsRequest\x1a\x1e.gitaly.ListPartitionsResponse\"\x08\xfa\x97(\x04\x08\x02\x10\x02\x42\x34Z2gitlab.com/gitlab-org/gitaly/v16/proto/go/gitalypbb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
    ["gitaly.PaginationParameter", "shared.proto"],
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Gitaly
  BackupPartitionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.BackupPartitionRequest").msgclass
  BackupPartitionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.BackupPartitionResponse").msgclass
  ListPartitionsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.ListPartitionsRequest").msgclass
  ListPartitionsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.ListPartitionsResponse").msgclass
  KVPair = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.KVPair").msgclass
end
