# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: partition.proto for package 'gitaly'

require 'grpc'
require 'partition_pb'

module Gitaly
  module PartitionService
    # PartitionService is a service providing RPCs accessing partitions as a whole.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'gitaly.PartitionService'

      # BackupPartition backs up an entire partition and saves it to
      # the configured backup sink (filesystem or object storage).
      rpc :BackupPartition, ::Gitaly::BackupPartitionRequest, ::Gitaly::BackupPartitionResponse
      # ListPartitions lists partitions present in the storage.
      rpc :ListPartitions, ::Gitaly::ListPartitionsRequest, ::Gitaly::ListPartitionsResponse
    end

    Stub = Service.rpc_stub_class
  end
end
