# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smarthttp.proto

require 'google/protobuf'

require 'lint_pb'
require 'packfile_pb'
require 'shared_pb'


descriptor_data = "\n\x0fsmarthttp.proto\x12\x06gitaly\x1a\nlint.proto\x1a\x0epackfile.proto\x1a\x0cshared.proto\"q\n\x0fInfoRefsRequest\x12,\n\nrepository\x18\x01 \x01(\x0b\x32\x12.gitaly.RepositoryB\x04\x98\xc6,\x01\x12\x1a\n\x12git_config_options\x18\x02 \x03(\t\x12\x14\n\x0cgit_protocol\x18\x03 \x01(\t\" \n\x10InfoRefsResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x86\x01\n$PostUploadPackWithSidechannelRequest\x12,\n\nrepository\x18\x01 \x01(\x0b\x32\x12.gitaly.RepositoryB\x04\x98\xc6,\x01\x12\x1a\n\x12git_config_options\x18\x02 \x03(\t\x12\x14\n\x0cgit_protocol\x18\x03 \x01(\t\"w\n%PostUploadPackWithSidechannelResponse\x12N\n\x1fpackfile_negotiation_statistics\x18\x01 \x01(\x0b\x32%.gitaly.PackfileNegotiationStatistics\"\xc1\x01\n\x16PostReceivePackRequest\x12,\n\nrepository\x18\x01 \x01(\x0b\x32\x12.gitaly.RepositoryB\x04\x98\xc6,\x01\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\r\n\x05gl_id\x18\x03 \x01(\t\x12\x15\n\rgl_repository\x18\x04 \x01(\t\x12\x13\n\x0bgl_username\x18\x05 \x01(\t\x12\x14\n\x0cgit_protocol\x18\x06 \x01(\t\x12\x1a\n\x12git_config_options\x18\x07 \x03(\t\"\'\n\x17PostReceivePackResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\xa0\x03\n\x10SmartHTTPService\x12Q\n\x12InfoRefsUploadPack\x12\x17.gitaly.InfoRefsRequest\x1a\x18.gitaly.InfoRefsResponse\"\x06\xfa\x97(\x02\x08\x02\x30\x01\x12R\n\x13InfoRefsReceivePack\x12\x17.gitaly.InfoRefsRequest\x1a\x18.gitaly.InfoRefsResponse\"\x06\xfa\x97(\x02\x08\x02\x30\x01\x12\x84\x01\n\x1dPostUploadPackWithSidechannel\x12,.gitaly.PostUploadPackWithSidechannelRequest\x1a-.gitaly.PostUploadPackWithSidechannelResponse\"\x06\xfa\x97(\x02\x08\x02\x12^\n\x0fPostReceivePack\x12\x1e.gitaly.PostReceivePackRequest\x1a\x1f.gitaly.PostReceivePackResponse\"\x06\xfa\x97(\x02\x08\x01(\x01\x30\x01\x42\x34Z2gitlab.com/gitlab-org/gitaly/v16/proto/go/gitalypbb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
    ["gitaly.Repository", "shared.proto"],
    ["gitaly.PackfileNegotiationStatistics", "packfile.proto"],
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Gitaly
  InfoRefsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.InfoRefsRequest").msgclass
  InfoRefsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.InfoRefsResponse").msgclass
  PostUploadPackWithSidechannelRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.PostUploadPackWithSidechannelRequest").msgclass
  PostUploadPackWithSidechannelResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.PostUploadPackWithSidechannelResponse").msgclass
  PostReceivePackRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.PostReceivePackRequest").msgclass
  PostReceivePackResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.PostReceivePackResponse").msgclass
end
