# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pkg/entity/entity.proto

require 'google/protobuf'

require 'buf/validate/validate_pb'


descriptor_data = "\n\x17pkg/entity/entity.proto\x12\x13gitlab.agent.entity\x1a\x1b\x62uf/validate/validate.proto\"\xa9\x02\n\tAgentMeta\x12!\n\x07version\x18\x01 \x01(\tB\x07\xbaH\x04r\x02(2R\x07version\x12(\n\tcommit_id\x18\x02 \x01(\tB\n\x18\x01\xbaH\x05r\x03(\xff\x01R\tcommit_id\x12-\n\rpod_namespace\x18\x03 \x01(\tB\x07\xbaH\x04r\x02(?R\rpod_namespace\x12$\n\x08pod_name\x18\x04 \x01(\tB\x08\xbaH\x05r\x03(\xff\x01R\x08pod_name\x12V\n\x12kubernetes_version\x18\x05 \x01(\x0b\x32&.gitlab.agent.entity.KubernetesVersionR\x12kubernetes_version\x12\"\n\x07git_ref\x18\x06 \x01(\tB\x08\xbaH\x05r\x03(\xff\x01R\x07git_ref\"\xa3\x01\n\x11KubernetesVersion\x12\x1d\n\x05major\x18\x01 \x01(\tB\x07\xbaH\x04r\x02(\x14R\x05major\x12\x1d\n\x05minor\x18\x02 \x01(\tB\x07\xbaH\x04r\x02(\x14R\x05minor\x12*\n\x0bgit_version\x18\x03 \x01(\tB\x08\xbaH\x05r\x03(\xff\x01R\x0bgit_version\x12$\n\x08platform\x18\x04 \x01(\tB\x08\xbaH\x05r\x03(\xff\x01R\x08platform\"\xcd\x01\n\nGitalyInfo\x12!\n\x07\x61\x64\x64ress\x18\x01 \x01(\tB\x07\xbaH\x04r\x02 \x01R\x07\x61\x64\x64ress\x12\x14\n\x05token\x18\x02 \x01(\tR\x05token\x12I\n\x08\x66\x65\x61tures\x18\x03 \x03(\x0b\x32-.gitlab.agent.entity.GitalyInfo.FeaturesEntryR\x08\x66\x65\x61tures\x1a;\n\rFeaturesEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"\xd0\x02\n\x10GitalyRepository\x12+\n\x0cstorage_name\x18\x02 \x01(\tB\x07\xbaH\x04r\x02 \x01R\x0cstorage_name\x12-\n\rrelative_path\x18\x03 \x01(\tB\x07\xbaH\x04r\x02 \x01R\rrelative_path\x12\x32\n\x14git_object_directory\x18\x04 \x01(\tR\x14git_object_directory\x12J\n git_alternate_object_directories\x18\x05 \x03(\tR git_alternate_object_directories\x12-\n\rgl_repository\x18\x06 \x01(\tB\x07\xbaH\x04r\x02 \x01R\rgl_repository\x12\x31\n\x0fgl_project_path\x18\x08 \x01(\tB\x07\xbaH\x04r\x02 \x01R\x0fgl_project_pathBGZEgitlab.com/gitlab-org/cluster-integration/gitlab-agent/v17/pkg/entityb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Gitlab
  module Agent
    module Entity
      AgentMeta = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitlab.agent.entity.AgentMeta").msgclass
      KubernetesVersion = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitlab.agent.entity.KubernetesVersion").msgclass
      GitalyInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitlab.agent.entity.GitalyInfo").msgclass
      GitalyRepository = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitlab.agent.entity.GitalyRepository").msgclass
    end
  end
end
