=begin
Apache Felix WebConsole

Client for Apache Felix Web Console API. List bundles, configure services, etc.

OpenAPI spec version: 4.3.0
Contact: bryan.stopp@gmail.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

# Common files
require 'apache_felix_webconsole_client/api_client'
require 'apache_felix_webconsole_client/api_error'
require 'apache_felix_webconsole_client/version'
require 'apache_felix_webconsole_client/configuration'

# Models
require 'apache_felix_webconsole_client/models/bundle'
require 'apache_felix_webconsole_client/models/bundle_list'
require 'apache_felix_webconsole_client/models/bundle_props'
require 'apache_felix_webconsole_client/models/bundle_state'

# APIs
require 'apache_felix_webconsole_client/api/bundle_api'

module ApacheFelix
  class << self
    # Customize default settings for the SDK using block.
    #   ApacheFelix.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
