module Datadog
  module AppSec
    module WAF
      class Context
        @context_obj: ::FFI::Pointer

        @valid: bool

        @retained: Array[untyped]

        RESULT_CODE: ::Hash[::Symbol, ::Symbol]

        attr_reader context_obj: ::FFI::Pointer

        def initialize: (Handle handle) -> void

        def finalize: () -> void

        def run: (WAF::data persistent_data, WAF::data ephemeral_data, ?::Integer timeout) -> ::Array[top]

        private

        def validate!: () -> void

        def invalidate!: () -> void

        def valid?: () -> bool?

        def valid!: () -> void

        def retained: () -> Array[untyped]

        def retain: (top object) -> void

        def release: (top object) -> void
      end
    end
  end
end
